# Generated by Django 5.2.7 on 2025-10-31 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('categoria', models.CharField(choices=[('VENDA', 'Venda'), ('INSUMO', 'Insumo'), ('SALARIO', 'Salário'), ('ESTOCAGEM', 'Estocagem'), ('DEPRECIACAO', 'Depreciação'), ('CAPITAL_INICIAL', 'Capital Inicial'), ('OUTROS', 'Outros')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('referencia_tabela', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_time_medio_dias', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salario_semanal', models.DecimalField(decimal_places=2, default=450.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('custo_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estoque_minimo', models.IntegerField(default=5000)),
                ('unidade_medida', models.CharField(default='un', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('custo_aquisicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_aquisicao', models.DateField()),
                ('capacidade_dia', models.IntegerField(default=500)),
                ('depreciacao_anual_percentual', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='LogEstoqueDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_log', models.DateField(unique=True)),
                ('quantidade_final_dia', models.IntegerField()),
                ('custo_estocagem_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lancado_financeiro', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_estoque_fabrica', to='loja.produto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
                ('quantidade', models.IntegerField()),
                ('referencia_tabela', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='fabrica.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoProdutoAcabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
                ('quantidade', models.IntegerField()),
                ('custo_producao_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('referencia_tabela', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_produto_acabado', to='loja.produto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('quantidade_planejada', models.IntegerField()),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('INSPECIONADA', 'Inspecionada')], default='PLANEJADA', max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='fabrica.funcionario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='fabrica.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='ControleQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField(auto_now_add=True)),
                ('quantidade_aprovada', models.IntegerField()),
                ('quantidade_rejeitada', models.IntegerField()),
                ('ordem_producao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle_qualidade', to='fabrica.ordemproducao')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('valor_total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='fabrica.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('custo_unitario_compra', models.DecimalField(decimal_places=4, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='fabrica.insumo')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fabrica.pedidocompra')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario_praticado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_fabrica', to='loja.produto')),
            ],
        ),
    ]
