# Generated by Django 5.2.7 on 2025-11-11 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlequalidade',
            name='inspetor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlequalidade',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlequalidade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='controlequalidade',
            name='data_inspecao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='controlequalidade',
            name='quantidade_aprovada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlequalidade',
            name='quantidade_rejeitada',
            field=models.IntegerField(default=0),
        ),
    ]
