# Generated by Django 5.2.7 on 2025-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0002_controlequalidade_inspetor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='quantidade_estoque',
            field=models.IntegerField(default=0),
        ),
    ]
