# Generated by Django 5.2.7 on 2025-11-11 22:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0003_insumo_quantidade_estoque'),
        ('loja', '0003_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='movimentoinsumo',
            old_name='data_movimento',
            new_name='data_hora',
        ),
        migrations.RenameField(
            model_name='movimentoprodutoacabado',
            old_name='data_movimento',
            new_name='data_hora',
        ),
        migrations.RenameField(
            model_name='ordemproducao',
            old_name='data_inicio',
            new_name='data_inicio_prevista',
        ),
        migrations.RenameField(
            model_name='ordemproducao',
            old_name='quantidade_planejada',
            new_name='quantidade_produzir',
        ),
        migrations.RemoveField(
            model_name='logestoquediario',
            name='data_log',
        ),
        migrations.RemoveField(
            model_name='logestoquediario',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='logestoquediario',
            name='quantidade_final_dia',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabrica.fornecedor'),
        ),
        migrations.AddField(
            model_name='logestoquediario',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='logestoquediario',
            name='insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs_estoque', to='fabrica.insumo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logestoquediario',
            name='movimentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logestoquediario',
            name='quantidade_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logestoquediario',
            name='quantidade_inicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maquina',
            name='capacidade_producao_hora',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='maquina',
            name='nome',
            field=models.CharField(default='Maquina Padrao', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='status_operacional',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('MANUTENCAO', 'Em Manutenção'), ('INOPERANTE', 'Inoperante')], default='OPERACIONAL', max_length=15),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_conclusao_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='produto_acabado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='loja.produto', verbose_name='Produto a Produzir'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fluxocaixa',
            name='categoria',
            field=models.CharField(choices=[('VENDA', 'Venda'), ('INSUMO', 'Insumo'), ('SALARIO', 'Salário'), ('CAPITAL_INICIAL', 'Capital Inicial'), ('OUTROS', 'Outros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fluxocaixa',
            name='data_lancamento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='pedido_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido_compra', to='fabrica.pedidocompra'),
        ),
        migrations.AlterField(
            model_name='movimentoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_insumo', to='fabrica.insumo'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO_TOTAL', 'Recebido Totalmente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
