# Generated by Django 5.2.7 on 2025-11-11 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0004_alter_ordemproducao_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='data_aquisicao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
