# Generated by Django 5.2.7 on 2025-11-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0005_ordemproducao_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoinsumo',
            name='custo_unitario_movimento',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_fornecidos', to='fabrica.fornecedor'),
        ),
    ]
