# Generated by Django 5.2.7 on 2025-11-12 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0006_movimentoinsumo_custo_unitario_movimento_and_more'),
        ('loja', '0003_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica.insumo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Composição do Produto',
                'verbose_name_plural': 'Composições dos Produtos',
                'unique_together': {('produto', 'insumo')},
            },
        ),
    ]
