# Generated by Django 5.2.7 on 2025-11-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
