# Generated by Django 5.2.7 on 2025-11-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado'), ('entregue', 'Entregue')], default='pendente', max_length=20),
        ),
    ]
