# Generated by Django 5.2.15 on 2026-06-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_remove_produto_imagem_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
